### PR TITLE
Legend component added

### PR DESCRIPTION
**Pull request by papriwalprateek**
Legend component added [ #3 ]
legend added in examples/scatter.rb example

### CODE REVIEW

**Comment by zuhao** [comment]
Looks good. Maybe you want to add some tests for it please?

**Comment by papriwalprateek** [comment]
@zuhao spec added.

**Comment by zuhao** [comment]
Thanks @papriwalprateek. :+1: 

One minor thing, next time please consider 2-space indentation for the code, for better consistency.

**Comment by papriwalprateek** [comment]
your welcome !
hmm ok.

**Comment by agarie** [comment]
Indentation should be changed before merging. :(

Good job, @papriwalprateek!

**Comment by translunar** [comment]
Yeah, I agree with @agarie. Please use two spaces instead of tabs. You should do the best you can to emulate the code style used in NMatrix and elsewhere in plotrb.

**Comment by translunar** [comment]
Is there a demo for this anywhere? I'm having a lot of trouble producing a legend. I can't figure out how to specify symbols or gradient, for example.

**Comment by papriwalprateek** [comment]
Hey John,

Check out this example
https://github.com/SciRuby/plotrb/blob/master/examples/scatter.rb. I have
added legend feature in this example.

BR,
Prateek

On Thu, Apr 24, 2014 at 10:44 PM, John Woods notifications@github.comwrote:

> Is there a demo for this anywhere? I'm having a lot of trouble producing a
> legend.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/SciRuby/plotrb/pull/13#issuecomment-41306898
> .

## 

Thanks and Regards
Prateek Papriwal
B.Tech, Electrical
IIT Delhi

**Pull request merged**
